### PR TITLE
fix: set plugin order to "post"

### PR DESCRIPTION
**Pull request by fi3ework**
Set the order to `"post"` to compact with rsbuild-plugin-dts as rsbuild-plugin-dts is set to `"post"` already, so the plugin need to wait dts plugin to emit dts files ahead.

### CODE REVIEW

**Review by chenjiahan — COMMENTED** [review]
Why `rsbuild-plugin-dts` use the post hook, can we change it to normal stage?

**Comment by fi3ework** [comment]
@Timeless0911 Just by looking at these few lines of code, I think it could be merged into one hook function with out using `"post"`, the integration test could also pass, what do you think? https://github.com/web-infra-dev/rslib/blob/3d5312dae6cbca23d07a78ce63a84154f31ed04c/packages/plugin-dts/src/index.ts#L138-L165.

**Comment by Timeless0911** [comment]
> @Timeless0911 Just by looking at these few lines of code, I think it could be merged into one hook function without using `"post"`, the integration test could also pass, what do you think? [web-infra-dev/rslib@`3d5312d`/packages/plugin-dts/src/index.ts#L138-L165](https://github.com/web-infra-dev/rslib/blob/3d5312dae6cbca23d07a78ce63a84154f31ed04c/packages/plugin-dts/src/index.ts#L138-L165).

This is to ensure that when dts of multiple formats are generated at the same time, errors in multiple `rsbuild-plugin-dts` can be all thrown before exiting process. Or it will look like:

image

The terminal responds to the exit code and exits, but the log is still outputting.

**Review by chenjiahan — APPROVED** [review]

**Comment by chenjiahan** [comment]
Released: https://github.com/rspack-contrib/rsbuild-plugin-publint/releases/tag/v0.2.1

**Pull request merged**
